# Generated by Django 4.2.3 on 2023-07-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easylearn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionform',
            old_name='message',
            new_name='address',
        ),
    ]
