# Generated by Django 4.2.3 on 2023-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easylearn', '0002_rename_message_admissionform_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
